# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - summer25wdp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # Chạy job build trên Windows
    permissions:
      contents: read # Cần quyền đọc để checkout code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "yarn" # Bật cache cho yarn
          cache-dependency-path: Backend/yarn.lock # Đường dẫn tới file lock để cache

      - name: YARN install, build, and test in Backend
        working-directory: ./Backend # Thư mục làm việc cho các lệnh yarn
        env: # Các biến môi trường này dành cho quá trình build và test (nếu cần)
          NODE_ENV: production
          PORT: ${{ secrets.PORT }} # Đảm bảo secret này được cấu hình trên GitHub
          MONGO_URL: ${{ secrets.MONGO_URL }} # Đổi từ MONGO_URI nếu secret của bạn là MONGO_URL
          JWT_SECRET: ${{ secrets.JWT_SECRET }} # Đảm bảo secret này được cấu hình trên GitHub
        run: |
          yarn install
          yarn build --if-present
          yarn test --if-present

      - name: Prepare deployment package
        shell: pwsh # Sử dụng PowerShell cho các lệnh trên Windows runner
        run: |
          New-Item -ItemType Directory -Force -Path deploy_package
          Copy-Item -Path Backend\dist\* -Destination deploy_package -Recurse -Force
          Copy-Item -Path Backend\package.json -Destination deploy_package -Force
          # Copy yarn.lock nếu tồn tại, quan trọng để Azure cài đặt đúng dependencies
          if (Test-Path Backend\yarn.lock) {
            Copy-Item -Path Backend\yarn.lock -Destination deploy_package -Force
          }
          Compress-Archive -Path deploy_package\* -DestinationPath release.zip -Force

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip # Tải lên file release.zip đã được chuẩn bị

  deploy:
    runs-on: ubuntu-latest # Job deploy có thể chạy trên Ubuntu
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # Tải về node-app (chứa release.zip)

      # Không cần bước giải nén nếu bạn deploy trực tiếp file .zip
      # - name: Unzip artifact for deployment
      #   run: unzip release.zip

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "summer25wdp"
          slot-name: "Production"
          package: release.zip # Deploy trực tiếp file release.zip
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_17d04d1aa3834efeb044b99e247a72bc }}
