name: Deploy NestJS App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Thay bằng phiên bản Node.js của bạn
          cache: "yarn"

      # Chạy yarn install trong thư mục Backend
      - name: Install dependencies
        working-directory: ./Backend # <--- THAY ĐỔI Ở ĐÂY
        run: yarn install --frozen-lockfile

      # Chạy yarn build trong thư mục Backend
      - name: Build application
        working-directory: ./Backend # <--- THAY ĐỔI Ở ĐÂY
        run: yarn build

      # Chuẩn bị gói deploy từ bên trong thư mục Backend
      - name: Prepare deployment package
        working-directory: ./Backend # <--- THAY ĐỔI Ở ĐÂY
        run: |
          # Tạo thư mục deploy_package ở thư mục gốc của checkout (bên ngoài thư mục Backend)
          mkdir ../deploy_package
          cp -R dist ../deploy_package/
          cp package.json ../deploy_package/
          cp yarn.lock ../deploy_package/
          # Sao chép thêm các file cần thiết khác nếu có

      # Bước sao chép file vẫn giữ nguyên source vì deploy_package được tạo ở gốc
      - name: Copy files to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          source: "./deploy_package/*" # Nguồn là nội dung của deploy_package đã tạo ở gốc
          target: ${{ secrets.AWS_TARGET_DIRECTORY }}
          strip_components: 1

      - name: Execute deployment commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.AWS_TARGET_DIRECTORY }}
            yarn install --production --frozen-lockfile
            # Thay 'your-app-name' hoặc 'backend' bằng tên ứng dụng PM2 của bạn
            pm2 restart backend || pm2 start dist/main.js --name backend
            pm2 save
            echo "Deployment completed"
