# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - summer25wdp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "yarn" # Thêm dòng này để cache các gói của Yarn, giúp tăng tốc độ build

      - name: Install dependencies in Backend (Yarn)
        working-directory: ./Backend
        run: yarn install

      - name: Build and test in Backend (Yarn)
        working-directory: ./Backend
        env: # Các biến môi trường này dành cho quá trình build và test
          NODE_ENV: production
          PORT: ${{ secrets.PORT }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          yarn build # Script "build" trong package.json của bạn là "nest build"
          yarn test --if-present # Giả sử bạn có script "test"

      - name: Zip artifact for deployment
        # Nén nội dung của thư mục Backend/dist (hoặc thư mục build output của bạn)
        # (cd Backend/dist && zip -r ../../release.zip .)
        #   - cd Backend/dist: Di chuyển vào thư mục build output.
        #   - zip -r ../../release.zip .: Nén toàn bộ nội dung của thư mục hiện tại (Backend/dist)
        #                                  vào file release.zip ở thư mục gốc của repository.
        run: (cd Backend/dist && zip -r ../../release.zip .) # <--- THAY ĐỔI: Chỉ nén output của Backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip # release.zip giờ chỉ chứa các file từ Backend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app # Tải về node-app (chứa release.zip)

      - name: Unzip artifact for deployment
        run: unzip release.zip # Giải nén release.zip, giờ đây thư mục hiện tại sẽ chứa các file từ Backend/dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D7F8B8AA99D4D5D86D2CA344D266D25 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5453BC304903408F88E5C3B6A9864801 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5D70EED4880C47D093DA525A43F51198 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "summer25wdp"
          slot-name: "Production"
          package: . # <--- Deploy nội dung đã giải nén (từ Backend/dist)
